# Generated by Django 2.1.5 on 2020-06-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersapi',
            options={'verbose_name': 'UsersAPI'},
        ),
    ]
