# Generated by Django 2.1.5 on 2020-06-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200615_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersapi',
            options={'verbose_name': 'UsersAPI', 'verbose_name_plural': 'UserAPI'},
        ),
    ]
