# Generated by Django 2.1.5 on 2020-06-16 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200615_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersapi',
            options={'verbose_name': 'UsersAPI', 'verbose_name_plural': 'UsersAPI'},
        ),
    ]
